In [29]:
from image_compression import jpeg_visualize
#jpeg_visualize()

In [12]:
from image_compression import get_gauss_1, get_gauss_2

In [15]:
#get_gauss_1()

In [16]:
#get_gauss_2()

In [21]:
block = np.arange(64).reshape(8, 8) + 100
block

array([[100, 101, 102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115],
       [116, 117, 118, 119, 120, 121, 122, 123],
       [124, 125, 126, 127, 128, 129, 130, 131],
       [132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147],
       [148, 149, 150, 151, 152, 153, 154, 155],
       [156, 157, 158, 159, 160, 161, 162, 163]])

In [22]:
index = np.array([0, 1, 8, 16, 9, 2, 3, 10, 
                  17, 24, 32, 25, 18, 11, 4, 5, 
                  12, 19, 26, 33, 40, 48, 41, 34, 
                  27, 20, 13, 6, 7, 14, 21, 28, 
                  35, 42, 49, 56, 57, 50, 43, 36, 
                  29, 22, 15, 23, 30, 37, 44, 51, 
                  58, 59, 52, 45, 38, 31, 39, 46, 
                  53, 60, 61, 54, 47, 55, 62, 63])

In [24]:
zz = block.reshape(-1)[index]
zz

array([100, 101, 108, 116, 109, 102, 103, 110, 117, 124, 132, 125, 118,
       111, 104, 105, 112, 119, 126, 133, 140, 148, 141, 134, 127, 120,
       113, 106, 107, 114, 121, 128, 135, 142, 149, 156, 157, 150, 143,
       136, 129, 122, 115, 123, 130, 137, 144, 151, 158, 159, 152, 145,
       138, 131, 139, 146, 153, 160, 161, 154, 147, 155, 162, 163])

In [27]:
zz[np.argsort(index)].reshape(8, 8)

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [10]:
result = []
bs = 2
for i in range(0, block.shape[0], bs):
    if i + bs > block.shape[0]:
            break
    for j in range(0, block.shape[1], bs):
        if j + bs > block.shape[1]:
            break
        result.append(block[i:i+bs, j:j+bs])
#result

NameError: name 'block' is not defined

In [46]:
blocks = [np.array([i]) for i in range(10)]
for b in blocks:
    b += 100
blocks

[array([100]),
 array([101]),
 array([102]),
 array([103]),
 array([104]),
 array([105]),
 array([106]),
 array([107]),
 array([108]),
 array([109])]

In [1]:
lst = [1,2,3,4,5,6,7]
it = iter(lst)

In [30]:
(11, 20) // 2

TypeError: unsupported operand type(s) for //: 'tuple' and 'int'